# Generated by Django 5.0.6 on 2025-01-14 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('script_generator', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='script',
            old_name='script',
            new_name='generated_script',
        ),
    ]
