# Generated by Django 5.0.6 on 2025-01-14 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('script_generator', '0002_rename_script_script_generated_script'),
    ]

    operations = [
        migrations.AddField(
            model_name='script',
            name='language',
            field=models.CharField(default='en', max_length=10),
        ),
    ]
